version: '3'
services:
  hybrid-agi-cli:
    image: hybrid-agi-cli:0.0.1
    working_dir: /HybridAGI
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hybrid-agi-cli
    env_file: .env
    depends_on:
      - redis
      - redis-insight
    volumes:
      - ./archives:/archives
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    depends_on:
      - redis
    ports:
      - 8001:8001

volumes:
  archives: