version: '3'
services:
  hybrid-agi:
    image: hybrid-agi:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hybrid-agi
    env_file: .env
    depends_on:
      - redis
      - redis-insight
    volumes:
      - ./archives:/HybridAGI/archives
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    depends_on:
      - redis
    ports:
      - 8001:8001