version: '3'
services:
  hybrid-agi-cli:
    image: hybrid-agi:0.1.0
    working_dir: /HybridAGI
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hybrid-agi
    env_file:
      - .env
    depends_on:
      - falkordb
      - redis-insight
    ports:
      - 8000:8000
    volumes:
      - ./archives:/HybridAGI/archives
      - ./documentation:/HybridAGI/documentation
      - ./programs:/HybridAGI/programs
  falkordb:
    image: falkordb/falkordb:latest
    container_name: falkordb
    ports:
      - 6379:6379
      - 7687:7687
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    depends_on:
      - falkordb
    ports:
      - 8001:8001