version: '3'
services:
  hybrid-agi-cli:
    image: hybrid-agi-cli:0.0.1
    working_dir: /HybridAGI
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hybrid-agi-cli
    env_file: .env
    depends_on:
      - falkordb
      - redis-insight
    volumes:
      - ./archives:/archives
  falkordb:
    image: falkordb/falkordb:latest
    container_name: falkordb
    ports:
      - "6379:6379"
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    depends_on:
      - falkordb
    ports:
      - 8001:8001

volumes:
  archives: