[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
allow-ambiguous-features = true

[project]
name = "hybridagi"
version = "0.0.2"
authors = [
    {name = "SynaLinks", email = "author@example.com"},
]
description = "The Programmable Neuro-Symbolic AGI"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "json"
    "pydantic",
    "python-dotenv",
    "coverage>=5.6",
    "colorama",
    "numpy",
    "redis>=4.5.2",
    "redisgraph",
    "langchain>=0.0.348",
    "openai",
    "tiktoken",
    "gpt4all",
    "text_generation",
    "duckduckgo-search",
]