[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "hybridagi"
version = "0.1.0"
authors = [
    {name = "SynaLinks", email = "author@example.com"},
]
description = "The Programmable Neuro-Symbolic AGI"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]