[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hybridagi"
version = "0.1.0"
authors = [
    {name = "SynaLinks", email = "author@example.com"},
]
description = "The Programmable Neuro-Symbolic AGI"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "langchain-community",
    "langchain-together",
    "fastapi[all]",
    "arxiv",
    "bs4",
    "pydantic",
    "python-dotenv",
    "coverage>=5.6",
    "colorama",
    "numpy",
    "redis>=4.5.2",
    "redisgraph",
    "langchain>=0.1.0",
    "tiktoken",
    "pypdf",
    "rapidocr-onnxruntime",
    "text_generation",
    "duckduckgo-search",
]